package assistant

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"strings"

	"github.com/acai-travel/tech-challenge/internal/chat/model"
	"github.com/acai-travel/tech-challenge/internal/chat/tool"
	"github.com/openai/openai-go/v2"
)

type Assistant struct {
	cli     openai.Client
	tools   tool.Map
	aiTools []openai.ChatCompletionToolUnionParam
}

func New(toolsMap tool.Map) *Assistant {
	return &Assistant{cli: openai.NewClient(),
		tools:   toolsMap,
		aiTools: toolsMap.OaiToolDefinitions()}
}

func (a *Assistant) Title(ctx context.Context, conv *model.Conversation) (string, error) {
	if len(conv.Messages) == 0 {
		return "An empty conversation", nil
	}

	slog.InfoContext(ctx, "Generating title for conversation", "conversation_id", conv.ID)

	//Avoid rewriting the msg generated by openAI
	msgs := make([]openai.ChatCompletionMessageParamUnion, len(conv.Messages)+1)

	msgs[0] = openai.SystemMessage("Generate a concise, descriptive title for the conversation based on the user message. The title should be a single line, no more than 80 characters, and should not include any special characters or emojis.")
	for i, m := range conv.Messages {
		if m.Role == model.RoleAssistant {
			msgs[i+1] = openai.AssistantMessage(m.Content)
		} else {
			msgs[i+1] = openai.UserMessage(m.Content)
		}
	}

	resp, err := a.cli.Chat.Completions.New(ctx, openai.ChatCompletionNewParams{
		Model:    openai.ChatModelO1,
		Messages: msgs,
	})

	if err != nil {
		return "", err
	}

	if len(resp.Choices) == 0 || strings.TrimSpace(resp.Choices[0].Message.Content) == "" {
		return "", errors.New("empty response from OpenAI for title generation")
	}

	title := resp.Choices[0].Message.Content
	title = strings.ReplaceAll(title, "\n", " ")
	title = strings.Trim(title, " \t\r\n-\"'")

	if len(title) > 80 {
		title = title[:80]
	}

	return title, nil
}

func (a *Assistant) Reply(ctx context.Context, conv *model.Conversation) (string, error) {
	if len(conv.Messages) == 0 {
		return "", errors.New("conversation has no messages")
	}

	slog.InfoContext(ctx, "Generating reply for conversation", "conversation_id", conv.ID)

	msgs := []openai.ChatCompletionMessageParamUnion{
		openai.SystemMessage("You are a helpful, concise AI assistant. Provide accurate, safe, and clear responses."),
	}

	for _, m := range conv.Messages {
		switch m.Role {
		case model.RoleUser:
			msgs = append(msgs, openai.UserMessage(m.Content))
		case model.RoleAssistant:
			msgs = append(msgs, openai.AssistantMessage(m.Content))
		}
	}

	for i := 0; i < 15; i++ {
		resp, err := a.cli.Chat.Completions.New(ctx, openai.ChatCompletionNewParams{
			Model:    openai.ChatModelGPT4_1,
			Messages: msgs,
			Tools:    a.aiTools,
		})

		if err != nil {
			return "", err
		}

		if len(resp.Choices) == 0 {
			return "", errors.New("no choices returned by OpenAI")
		}

		if message := resp.Choices[0].Message; len(message.ToolCalls) > 0 {
			msgs = append(msgs, message.ToParam())

			for _, call := range message.ToolCalls {
				slog.InfoContext(ctx, "Tool call received", "name", call.Function.Name, "args", call.Function.Arguments)

				toolName := call.Function.Name

				var args map[string]any
				if err := json.Unmarshal([]byte(call.Function.Arguments), &args); err != nil {
					msgs = append(msgs, openai.ToolMessage("failed to parse tool call arguments: "+err.Error(), call.ID))
					break
				}

				result, err := a.executeTool(ctx, toolName, args)

				if err != nil {
					slog.ErrorContext(ctx, "Tool execution failed", "tool", toolName, "error", err)
					msgs = append(msgs, openai.ToolMessage("Tool"+toolName+" failed with error: "+err.Error(), call.ID))
				} else {
					msgs = append(msgs, openai.ToolMessage(result, call.ID))
				}

			}

			continue
		}

		return resp.Choices[0].Message.Content, nil
	}

	return "", errors.New("too many tool calls, unable to generate reply")
}

func (a *Assistant) executeTool(ctx context.Context, toolName string, args map[string]any) (string, error) {
	tool, err := a.tools.GetToolByName(toolName)
	if err != nil {
		// Failure to find the tool, either not registered or mismatch
		// between aiTools and tools map.
		slog.WarnContext(ctx, "Model requested unknown tool", "tool", toolName)
		return "", fmt.Errorf("error: tool '%s' is not registered or implemented", toolName)
	}

	// Execute the specific tool
	toolResult, err := tool.Execute(ctx, args)
	if err != nil {
		return "", fmt.Errorf("execution error in %s: %w", toolName, err)
	}

	return toolResult, nil
}
